### PR TITLE
XE6 + major speed improvement + Windows Server

### PR DESCRIPTION
**Pull request by andremussche**
I used your great project to track down some high memory usage issues, thanks!

I had to fix some stuff in order to make it work on a Windows Server version (page_execute rights in the injection dll) and I made some big speed improvements (it was unworkable slow in a large project).

### CODE REVIEW

**Comment by yavfast** [comment]
Ok. Great work!

**Comment by hvassbotn** [comment]
Hi André and Yav,

Nice project! I've had some use of it for profiling, although it is a bit slow... Will test more with your changes, André. 

Yav: is the pre-compiled version here http://dbg-spider.net/ the new faster one?

/Hallvard

**Comment by yavfast** [comment]
These commits speed up view information in the tree and support XE6. 
For speed up, use single profiler in settings and turn off the rest.

**Comment by hvassbotn** [comment]
I see. I tried to turn off other profilers, but could not detect much change. Much of the same statistics seemed to be collected  

I hope to have the time to look more into the code and see if I can contribute. I like the accumulation into unit level. It could be useful to accumulate into class level as well.

**Pull request merged**
